OBMC_IMAGE_EXTRA_INSTALL:append = " persistent-net-name dpinit program-edid"
OBMC_IMAGE_EXTRA_INSTALL:remove = " nvidia-fdr"
OBMC_IMAGE_EXTRA_INSTALL:remove = " nvidia-bmc-compliance"
OBMC_IMAGE_EXTRA_INSTALL:remove = " nvidia-mc-aspeed-lib"
OBMC_IMAGE_EXTRA_INSTALL:remove = " nvidia-otp-monitor"
